### ISSUE TITLE
Download limit

### ISSUE THREAD

**Issue by Chris-YiMing** [wtekiela/opensub4j#13]
Why are downloads still 200 when logged in using OpenSub4j's VIP account?

**Comment by Chris-YiMing** [comment]
URL serverUrl = new URL("https", "api.opensubtitles.org", 443, "/xml-rpc");
OpenSubtitlesClient osClient = new OpenSubtitlesClientImpl(serverUrl);
osClient.login("user", "password", "en", "TemporaryUserAgent");

**Comment by wtekiela** [comment]
This might be because you are using `TemporaryUserAgent`. I think if you want to bypass the limits, you will need to register your application with opensubtitles. Refer to this documentation for details: https://trac.opensubtitles.org/projects/opensubtitles/wiki/DevReadFirst#Howtorequestanewuseragent
